In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [7]:
data.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [9]:
data.duplicated().sum()

0

In [10]:
data.head(1)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  

[1 rows x 21 columns]

In [17]:
x= data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [22]:
y= data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=25, test_size=0.25)

In [26]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()
classifier.fit(x_train,y_train)

C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [28]:
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [33]:
y_pred = classifier.predict(x_test)
y_pred

array([2, 2, 3, 1, 2, 1, 1, 2, 1, 3, 1, 0, 0, 2, 1, 3, 1, 1, 3, 0, 2, 1,
       3, 1, 2, 2, 1, 0, 3, 1, 3, 0, 3, 0, 3, 3, 0, 3, 3, 1, 1, 3, 3, 1,
       3, 1, 0, 3, 1, 2, 3, 0, 0, 3, 0, 2, 3, 0, 0, 1, 0, 3, 2, 0, 3, 1,
       0, 0, 1, 3, 1, 2, 0, 3, 3, 1, 2, 1, 2, 3, 0, 2, 0, 0, 1, 0, 3, 2,
       1, 2, 2, 2, 3, 3, 3, 3, 1, 1, 3, 2, 1, 2, 1, 1, 1, 3, 3, 3, 2, 0,
       2, 1, 2, 1, 2, 1, 0, 3, 3, 2, 2, 2, 2, 3, 2, 2, 2, 1, 3, 2, 1, 3,
       0, 3, 2, 1, 1, 2, 3, 1, 1, 3, 2, 3, 1, 1, 2, 0, 2, 2, 3, 1, 0, 3,
       1, 1, 0, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 1, 3, 0, 0, 2, 1, 2, 2, 3,
       3, 1, 1, 3, 0, 0, 1, 3, 0, 3, 3, 2, 1, 3, 3, 3, 3, 2, 1, 1, 1, 2,
       3, 1, 3, 1, 0, 1, 0, 0, 2, 3, 3, 1, 2, 0, 0, 3, 2, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 3, 3, 3, 3, 3, 2, 3, 2, 0,
       2, 2, 0, 3, 2, 2, 1, 1, 0, 0, 3, 3, 2, 3, 2, 3, 3, 1, 1, 3, 3, 0,
       3, 1, 0, 3, 0, 2, 1, 0, 1, 3, 1, 3, 2, 1, 2, 3, 0, 0, 0, 2, 1, 2,
       3, 3, 3, 0, 2, 1, 0, 3, 0, 0, 1, 1, 0, 1, 2,

In [34]:
classifier.score(x_test,y_test)*100

64.8

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

64.8

In [36]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[91, 33,  1,  0],
       [14, 73, 26, 10],
       [ 0, 32, 67, 35],
       [ 0,  0, 25, 93]], dtype=int64)

# K-Nearest Neighbour

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
data=pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [40]:
data.shape

(2000, 21)

In [45]:
x=data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [44]:
y=data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=25, test_size=0.25)

In [53]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train =sc_x.fit_transform(x_train)
x_test= sc_x.fit_transform(x_test)

In [55]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,p=2, metric="minkowski")
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [57]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 2, 2, 2, 2, 1, 1, 1, 3, 2, 0, 0, 0, 0, 1, 1, 2, 1, 0, 3, 2,
       2, 1, 1, 2, 0, 0, 1, 1, 3, 2, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 3, 2,
       2, 2, 1, 2, 0, 1, 3, 0, 0, 3, 1, 2, 1, 0, 1, 1, 0, 3, 2, 1, 3, 0,
       0, 0, 0, 2, 1, 0, 0, 3, 3, 1, 1, 0, 1, 2, 0, 3, 0, 1, 0, 0, 0, 3,
       1, 1, 2, 1, 3, 2, 2, 3, 0, 2, 2, 2, 2, 0, 1, 2, 3, 2, 2, 2, 2, 1,
       1, 1, 0, 2, 2, 0, 0, 3, 3, 2, 3, 1, 1, 3, 2, 1, 3, 0, 3, 2, 2, 3,
       1, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1, 3, 1, 2, 0, 0, 2, 0, 2, 1, 0, 1,
       0, 0, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 0, 0, 2, 1, 2, 2, 3,
       3, 1, 0, 2, 0, 0, 2, 0, 0, 1, 1, 1, 2, 2, 3, 3, 2, 2, 0, 3, 0, 3,
       3, 1, 1, 0, 0, 2, 0, 1, 2, 2, 3, 2, 1, 0, 0, 0, 2, 1, 0, 3, 0, 0,
       0, 2, 0, 0, 1, 1, 2, 2, 1, 3, 1, 0, 2, 3, 1, 3, 2, 3, 0, 3, 2, 0,
       1, 1, 0, 2, 0, 1, 3, 1, 0, 0, 2, 2, 3, 2, 2, 3, 2, 0, 0, 3, 2, 1,
       3, 1, 0, 1, 0, 3, 3, 0, 1, 2, 1, 1, 2, 1, 0, 3, 0, 0, 0, 0, 2, 3,
       3, 3, 0, 0, 3, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0,

In [58]:
classifier.score(x_test,y_test)*100

48.0

In [59]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[86, 33,  6,  0],
       [48, 39, 30,  6],
       [14, 54, 52, 14],
       [ 2, 15, 38, 63]], dtype=int64)

# Support Vector Classification


In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [61]:
data = pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [65]:
x=data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [66]:
y=data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [85]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=50, test_size=0.25)

In [86]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(x_train,y_train)

SVC()

In [87]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 3, 0, 3, 1, 2, 1, 3, 1, 3, 3, 3, 1, 3, 2, 1, 0, 3, 2, 2, 2, 3,
       2, 3, 0, 2, 2, 0, 1, 0, 3, 1, 1, 3, 0, 1, 2, 0, 3, 0, 2, 1, 2, 2,
       1, 3, 1, 0, 1, 1, 2, 1, 0, 0, 2, 2, 1, 1, 0, 1, 3, 3, 1, 0, 3, 0,
       3, 2, 3, 2, 1, 3, 2, 1, 0, 3, 3, 1, 3, 1, 1, 1, 1, 2, 1, 0, 1, 1,
       3, 2, 1, 3, 0, 1, 3, 3, 1, 0, 2, 1, 1, 3, 3, 2, 0, 0, 1, 1, 3, 0,
       3, 3, 2, 0, 0, 2, 1, 3, 2, 3, 1, 1, 0, 2, 3, 0, 0, 3, 2, 2, 2, 3,
       2, 3, 3, 0, 3, 1, 3, 1, 3, 1, 0, 0, 2, 2, 1, 0, 0, 3, 2, 1, 2, 0,
       0, 2, 3, 3, 2, 0, 1, 2, 3, 3, 3, 0, 3, 1, 3, 1, 1, 0, 3, 2, 2, 2,
       2, 0, 0, 1, 1, 2, 2, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 1,
       1, 1, 3, 2, 3, 2, 0, 0, 2, 1, 0, 3, 2, 0, 1, 2, 2, 1, 3, 1, 0, 1,
       2, 0, 2, 3, 3, 3, 2, 2, 3, 0, 0, 2, 2, 1, 0, 0, 3, 0, 0, 0, 1, 3,
       0, 3, 0, 3, 3, 1, 1, 3, 1, 1, 0, 2, 2, 2, 1, 0, 0, 3, 3, 0, 2, 2,
       0, 2, 2, 2, 3, 3, 0, 1, 3, 2, 3, 3, 0, 2, 1, 2, 3, 3, 0, 3, 1, 1,
       1, 3, 1, 1, 1, 2, 0, 3, 2, 3, 1, 1, 2, 2, 3,

In [88]:
round(classifier.score(x_test,y_test)*100,2)

94.8

In [89]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

94.8

In [90]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
cm

array([[117,   2,   0,   0],
       [  1, 125,   2,   0],
       [  0,   8, 112,   4],
       [  0,   0,   9, 120]], dtype=int64)

# Naive Bayes Classification

In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [93]:
data = pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [95]:
x=data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [96]:
y = data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [97]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=25,test_size=0.25)

In [98]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [99]:
x_train

array([[ 0.82573221,  1.02020406,  1.57457914, ...,  0.55270519,
         0.99866755, -1.00267023],
       [ 1.68227568, -0.98019606,  0.83595659, ...,  0.55270519,
         0.99866755, -1.00267023],
       [ 0.2220513 ,  1.02020406, -1.25680731, ...,  0.55270519,
         0.99866755, -1.00267023],
       ...,
       [ 1.62988074, -0.98019606, -0.76439227, ..., -1.80928281,
        -1.00133422,  0.99733688],
       [-1.69605935, -0.98019606, -0.88749603, ...,  0.55270519,
        -1.00133422, -1.00267023],
       [ 1.09226302, -0.98019606, -0.88749603, ..., -1.80928281,
         0.99866755,  0.99733688]])

In [103]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [104]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 3, 0, 2, 1, 1, 2, 1, 3, 1, 0, 1, 1, 1, 2, 1, 2, 3, 0, 1, 1,
       2, 0, 2, 2, 1, 0, 3, 1, 3, 1, 2, 0, 2, 3, 0, 1, 2, 1, 1, 2, 3, 2,
       3, 1, 0, 2, 1, 2, 3, 0, 1, 3, 0, 3, 1, 0, 0, 0, 1, 2, 2, 0, 3, 1,
       1, 0, 1, 1, 0, 1, 0, 3, 3, 1, 3, 2, 2, 3, 0, 3, 0, 0, 0, 0, 2, 2,
       2, 2, 3, 1, 3, 3, 2, 3, 1, 1, 2, 2, 1, 2, 1, 2, 2, 3, 2, 3, 3, 0,
       1, 1, 2, 1, 1, 1, 0, 3, 3, 1, 3, 1, 2, 3, 1, 2, 3, 1, 3, 2, 1, 2,
       0, 3, 2, 1, 1, 2, 3, 0, 2, 3, 2, 3, 1, 1, 1, 0, 2, 1, 3, 2, 0, 3,
       1, 2, 0, 2, 1, 2, 3, 2, 1, 0, 2, 0, 2, 1, 3, 0, 0, 2, 1, 2, 2, 3,
       3, 1, 0, 3, 0, 0, 1, 1, 0, 2, 3, 2, 2, 3, 3, 2, 2, 3, 1, 1, 0, 3,
       3, 1, 3, 0, 0, 1, 0, 0, 3, 3, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 2, 3, 1, 1, 3, 2, 1, 3, 3, 2, 3, 1, 3, 2, 3, 2, 0,
       1, 2, 0, 2, 3, 2, 2, 0, 0, 1, 3, 2, 2, 3, 2, 3, 2, 1, 1, 3, 3, 0,
       3, 1, 0, 3, 0, 1, 1, 0, 1, 2, 0, 1, 2, 1, 1, 3, 0, 0, 0, 1, 2, 3,
       3, 3, 1, 0, 3, 0, 0, 1, 0, 0, 1, 2, 1, 1, 2,

In [105]:
classifier.score(x_test,y_test)*100

79.60000000000001

In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

79.60000000000001

In [108]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[107,  18,   0,   0],
       [  7,  94,  22,   0],
       [  0,  28,  91,  15],
       [  0,   0,  12, 106]], dtype=int64)

# Decision Tree Classification


In [109]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [112]:
data= pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [115]:
x =data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [116]:
y=data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [119]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=25, test_size=0.25)

In [120]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [124]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state=50)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=50)

In [125]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 1, 3, 0, 2, 1, 0, 2, 1, 3, 1, 0, 1, 1, 1, 2, 1, 2, 3, 0, 1, 1,
       2, 0, 2, 3, 1, 0, 3, 0, 3, 2, 2, 1, 1, 3, 0, 1, 2, 0, 1, 2, 3, 2,
       3, 1, 0, 3, 1, 2, 3, 0, 0, 3, 1, 3, 1, 0, 0, 0, 1, 2, 2, 1, 3, 1,
       1, 0, 1, 2, 0, 1, 0, 3, 3, 1, 3, 2, 1, 3, 0, 2, 0, 0, 0, 0, 2, 2,
       2, 3, 3, 2, 3, 3, 2, 3, 0, 2, 2, 2, 1, 1, 1, 2, 2, 3, 2, 3, 3, 0,
       1, 1, 1, 1, 1, 1, 0, 3, 3, 1, 3, 2, 2, 2, 1, 2, 3, 1, 3, 2, 1, 2,
       0, 3, 3, 1, 1, 1, 2, 0, 2, 3, 2, 2, 1, 0, 2, 0, 3, 1, 3, 2, 0, 3,
       1, 1, 1, 2, 0, 2, 3, 2, 1, 0, 2, 0, 3, 2, 2, 0, 0, 2, 2, 2, 3, 3,
       2, 1, 0, 2, 0, 0, 1, 2, 0, 2, 2, 2, 1, 3, 3, 2, 2, 2, 1, 1, 0, 3,
       3, 2, 3, 0, 0, 1, 0, 0, 3, 2, 3, 1, 2, 1, 0, 2, 2, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 3, 1, 3, 2, 3, 1, 3, 1, 0,
       1, 2, 0, 1, 2, 3, 2, 0, 0, 0, 3, 2, 3, 3, 2, 3, 1, 2, 1, 3, 3, 0,
       3, 1, 0, 2, 0, 2, 1, 0, 1, 2, 0, 2, 2, 1, 1, 3, 0, 0, 0, 1, 2, 3,
       3, 3, 1, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 1, 2,

In [126]:
classifier.score(x_test,y_test)*100

84.6

In [127]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

84.6

In [128]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[116,   9,   0,   0],
       [  8, 106,   9,   0],
       [  0,  19,  98,  17],
       [  0,   0,  15, 103]], dtype=int64)

# Random Forest Classification

In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [131]:
data = pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [132]:
x=data.iloc[:,:-1].values
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [133]:
y=data.iloc[:,-1].values
y

array([1, 2, 2, ..., 3, 0, 3], dtype=int64)

In [134]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, random_state=25, test_size=0.25)

In [136]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=300)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=300)

In [137]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 3, 0, 1, 1, 1, 2, 1, 3, 1, 0, 1, 1, 1, 2, 1, 2, 3, 0, 1, 1,
       2, 0, 2, 3, 1, 0, 3, 1, 3, 1, 2, 0, 1, 3, 0, 1, 2, 1, 1, 2, 3, 2,
       3, 1, 0, 3, 1, 2, 3, 0, 0, 3, 0, 3, 1, 0, 0, 0, 1, 2, 2, 0, 3, 1,
       1, 0, 1, 2, 0, 1, 0, 3, 3, 1, 3, 2, 2, 3, 0, 3, 0, 0, 0, 0, 2, 2,
       2, 2, 3, 2, 3, 3, 2, 3, 0, 2, 2, 2, 1, 2, 1, 2, 2, 3, 2, 3, 3, 0,
       1, 1, 1, 1, 1, 1, 0, 3, 3, 1, 3, 1, 2, 3, 2, 2, 3, 1, 3, 2, 1, 3,
       0, 3, 3, 1, 1, 1, 3, 0, 2, 3, 2, 2, 1, 1, 1, 0, 2, 1, 3, 2, 0, 3,
       1, 1, 0, 2, 1, 2, 3, 2, 1, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2, 2, 2, 3,
       3, 1, 0, 3, 0, 0, 1, 1, 0, 2, 2, 2, 1, 3, 3, 2, 2, 2, 1, 1, 0, 3,
       3, 1, 3, 0, 0, 1, 0, 0, 2, 3, 3, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 3, 2, 3, 1, 3, 1, 3, 1, 0,
       1, 2, 0, 1, 3, 3, 2, 0, 0, 0, 3, 2, 2, 3, 2, 3, 1, 2, 1, 3, 3, 0,
       3, 1, 0, 2, 0, 1, 1, 0, 1, 3, 0, 2, 2, 2, 1, 3, 0, 0, 0, 1, 2, 3,
       3, 3, 1, 0, 3, 1, 0, 1, 0, 0, 0, 2, 1, 1, 2,

In [ ]:
classifier.score(x_tst)